# Creating/editing pages {#addPage}

Before we can make a wiki, we have to know how to do basic edits to a page. You'd be surprised at how many things require special attention to modify on the wiki.

If you've ever made your own website before, you may have had to just upload all the relevant files and immediately have a website that you could use. iGEM's uses **MediaWiki**, which **requires** you to type in the HTML for every individual page. Controversially, a lot of web programmers dislike this model, because it increases complexity if they want to do complex stuff. However, note that using MediaWiki is a godsend for some teams that don't have any knowledge of web programming. That is why there will likely be *no change* to this structure for years to come.

For any demonstrations, all demonstration pages will use a page from [Team:Washington's iGEM Wiki](http://2017.igem.org/Team:Washington).

## Wiki pages structure {#structure}

The iGEM wiki is structured in a very straightforward manner.

`http://[YEAR].igem.org/Team:[TEAM]` will lead you to the main page. Take note that there is **no backslash** after this. If you have a backslash, then you will go to a blank uncreated page.

There are many special pages that the judges take into consideration for determining what medal you will receive at the Jamboree. These pages can be found [here](http://2017.igem.org/Judging/Pages_for_Awards). For example, the `Attributions` page for your team will follow the structure `http://[YEAR].igem.org/Team:[TEAM]/Attributions`.

Additionally, the human practices pages are a bit funky, but they follow the same structure, they just have a `/HP/` before them. You *shouldn't* think about this as if it was a file pathway, but rather a page with the page title `/HP/Gold_Integrated` or so.

## Working off a judged page {#existingPage}

All the special pages noted in section \@ref(structure) will be an existing page for you to work on. It looks something like the following:  

## Creating a new blank page {#blankPage}

## Making a template for code {#template}

## Including JavaScript and CSS {#includingJSCSS}

## Overriding iGEM CSS

## Using templates to put them all together {#putTogether}
