---
title: "A guide to writing an iGEM Wiki"
author: "William Kwok"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a book to teach you the ins and outs of writing a wiki page"
---

# Preface {#preface}

Writing an iGEM wiki will be undoubtably one of the **most frustrating** things every team has to face. Some teams have members that have never touched an ounce of HTML, while some others have members dedicated to writing a wiki. Regardless, there are many obstacles that will be faced in the process of making a wiki whether you are a novice or professional at programming on the client-side.

We have compiled a list of *important* things to know before you start going with your wiki. This book assumes you have some knowledge of programming in HTML, CSS, and JavaScript (optional).

**Additionally, this book will also teach those on the Washington iGEM team how to work with the JavaScript created from the previous years' wiki. This message will self-destruct if we make this tutorial public for the rest of iGEM.**



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
